config/routes.rb
Rails.application.routes.draw do

root "houses#index"
get 'access/index', :to=>"access#index"
get 'access/logout', :to=>"access#logout"
get 'access/login', :to=>"access#login"
post 'access/attempt_login', :to=>"access#attempt_login" 

  resources :houses do
    member do
      get 'delete'
    end
  end

  resources :energies do
    member do
      get 'delete'
    end
  end

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
	has_secure_password
end

app/models/energy.rb
class Energy < ActiveRecord::Base
	# associations
	belongs_to :house

	# data validations
	validates :year, :presence=>true,
					 :numericality=> true

	validates :month, :presence=>true,
					  :numericality=> true

	validates :temperature, :presence=>true,
					        :numericality=> true

	validates :daylight, :presence=>true,
					     :numericality=> true

	validates :energy_production, :presence=>true,
					 			  :numericality=> true
end

app/models/house.rb
class House < ActiveRecord::Base
	# associations
	has_many :energies

	# data validation
	validates :first_name, :presence=> true,
						   :numericality=> false

	validates :last_name, :presence=> true,
						  :numericality=> false

	validates :city, :presence=> true,
					 :numericality=> false

	validates :num_of_people, :presence=> true,
						   :numericality=> true

	validates :has_child, :inclusion => {:in => [true, false]}

end

app/controllers/access_controller.rb
class AccessController < ApplicationController
  before_action :confirm_logged_in, :except=>[:login, :attempt_login, :logout]

  def index
  	# display text & links
  end

  def login
  	# login form
  end

  def attempt_login
  	if params[:username].present? && params[:password].present?
  		found_user=AdminUser.where(:username=>params[:username]).first
  		if found_user
  			authorized_user=found_user.authenticate(params[:password])
  		end
  	end
  	if authorized_user
  		# mark user as logged in
  		session[:user_id]=authorized_user.id
  		session[:username]=authorized_user.username
  		flash[:notice]= "You are logged in."
  		redirect_to(:action=>'index')
  	else
  		flash[:error]="Invalid username/password combination."
  		redirect_to(:action=>'login')
  	end
  end

  def logout
  	# mark user as logged out
  	session[:user_id]=nil
  	session[:username]=nil
  	flash[:notice]="Logged out"
  	redirect_to(:action=>'login')
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
  def confirm_logged_in
  	unless session[:user_id]
  		flash[:notice]="Please log in."
  		redirect_to("/access/login")
  		return false # halts the before_action
  	else
  		return true
  	end
  end
end

app/controllers/energies_controller.rb
class EnergiesController < ApplicationController
	before_action :confirm_logged_in, :except=>[:index]
	
	def index
		@energies=Energy.all
	end
	
	def new
	    @energy=Energy.new
    end

    def create
    	# Instantiate a new object using form parameters
    	@energy=Energy.new(energy_params)
	    # Save the object
	    if @energy.save
	      # If save succeeds, redirect to the index action
	      flash[:notice]="saved sucessfully"
	      redirect_to(:action=>'index')
	    else
	      # If save fails, redisplay the form so user can fix problems
	      render('new')
	    end
	end

    def edit
    	@energy=Energy.find(params[:id])
    end

    def update
	    # Find an existing object using form parameters
	    @energy=Energy.find(params[:id])
	    
	    # Update the object
	    if @energy.update_attributes(energy_params)
	      # If update succeeds, redirect to the index action
	      flash[:notice]="updated successfully"
	      redirect_to(:action=>'index')
	    else
	      # If update fails, redisplay the form so user can fix problems
	      render('edit')
	    end
	end

  	def delete
    	@energy=Energy.find(params[:id])
  	end

  	def destroy
    	energy=Energy.find(params[:id]).destroy
    	flash[:notice]="Energy Record #{energy.id} destroyed successfully"
    	redirect_to(:action=>'index')
	end

	private
	    def energy_params
	      params.require(:energy).permit(:label,:house_id,:year,:month,:temperature,:daylight,:energy_production)
    end
end

app/controllers/houses_controller.rb
class HousesController < ApplicationController
	before_action :confirm_logged_in, :except=>[:index, :show]
	def index
		@houses=House.all
	end

	def show
		@house=House.find(params[:id])
		@energies=@house.energies
	end

	def new
	    @house=House.new
    end

    def create
    	# Instantiate a new object using form parameters
    	@house=House.new(house_params)
	    # Save the object
	    if @house.save
	      # If save succeeds, redirect to the index action
	      flash[:notice]="saved sucessfully"
	      redirect_to(:action=>'index')
	    else
	      # If save fails, redisplay the form so user can fix problems
	      render('new')
	    end
	end

    def edit
    	@house=House.find(params[:id])
    end

    def update
	    # Find an existing object using form parameters
	    @house=House.find(params[:id])
	    
	    # Update the object
	    if @house.update_attributes(house_params)
	      # If update succeeds, redirect to the index action
	      flash[:notice]="updated successfully"
	      redirect_to(:action=>'index')
	    else
	      # If update fails, redisplay the form so user can fix problems
	      render('edit')
	    end
	end

  	def delete
    	@house=House.find(params[:id])
  	end

  	def destroy
    	house=House.find(params[:id]).destroy
    	flash[:notice]="House #{house.id} destroyed successfully"
    	redirect_to(:action=>'index')
	end

	private
	    def house_params
	      params.require(:house).permit(:first_name,:last_name,:city,:num_of_people,:has_child)
    end
end

app/helpers/access_helper.rb
module AccessHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def error_messages_for(object)
		render(:partial=>'application/error_messages',
			:locals=>{:object=>object})
	end
end

app/helpers/energy_helper.rb
module EnergyHelper
end

app/helpers/house_helper.rb
module HouseHelper
end

app/views/access/index.html.erb
<% @page_title= "Admin Menu" %>

<div class="menu">
	<h2>Admin Menu</h2>
	<div class="identity">Logged in as: <%= session[:username]%></div>
	<ul>
		<li><%= link_to("Manage Energy Records", energies_path)%></li>
		<li><%= link_to("Manage Houses", houses_path)%></li>
		<li><%= link_to("Logout",:action=>'logout')%></li>
	</ul>
</div>

app/views/access/login.html.erb
<% @page_title = "Admin Login"%>
<%= link_to("<< Back to House List",houses_path) %><br/>
<%= link_to("<< Back to Energy Record List",energies_path) %>
<div class="login">
	<fieldset>
	<legend>Log In</legend>
	<%= form_tag(:action=>'attempt_login') do %>
	<table>
		<tr>
			<td>User Name</td>
			<td><%= text_field_tag(:username) %></td>
		</tr>
		<tr>
			<td>Password</td>
			<td><%= password_field_tag(:password)%></td>
		</tr>
		<tr>
			<td>&nbsp;</td>
			<td><%= submit_tag("Log In") %></td>
		</tr>
	</table>
	<% end %>
	</fieldset>
</div>

app/views/application/_error_messages.html.erb
<% if object && object.errors.size > 0 %>
	<div class="error">
		<h2><%= pluralize(object.errors.size, "error")%> prohibited
			this record from being saves</h2>
		<p>There were problems with the following fields:</p>
		<ul>
		<% object.errors.full_messages.each do |msg| %>
			<li><%= msg%></li>
		<% end %>
		</ul>
	</div>
<% end %>

app/views/energies/_form.html.erb
<%= error_messages_for(@energy) %>

<table>
	<tr>
		<th><%= f.label(:label)%></th>
		<td><%= f.text_field(:label,:class=>"text")%></td>
	</tr>
	<tr>
		<th><%= f.label(:house_id)%></th>
		<td><%= f.text_field(:house_id,:class=>"text")%></td>
	</tr>
	<tr>
		<th><%= f.label(:year)%></th>
		<td><%= f.select(:year,1950..2050)%></td>
	</tr>
	<tr>
		<th><%= f.label(:month)%></th>
		<td><%= f.select(:month,1..12)%></td>
	</tr>
	<tr>
		<th><%= f.label(:temperature)%></th>
		<td><%= f.text_field(:temperature,:class=>"text")%></td>
	</tr>
	<tr>
		<th><%= f.label(:daylight)%></th>
		<td><%= f.text_field(:daylight,:class=>"text")%></td>
	</tr>
	<tr>
		<th><%= f.label(:energy_production)%></th>
		<td><%= f.text_field(:energy_production,:class=>"text")%></td>
	</tr>

</table>

app/views/energies/delete.html.erb
<% @page_title="Energy Delete"%>
<%= link_to("<< Back to Energy Record List",energies_path) %><br/>
<%= link_to("<< Back to House List",houses_path) %>

<div class="energies delete">
	<fieldset>
	<legend>Delete Energy</legend>

	<%= form_for(:energy, :url=>{:action=>"destroy",:id=>@energy.id}) do |f| %>

		<p><strong>Are you sure you want to delete this energy record?</strong></p>

		<table class="listing" summary="Energy list">
			<tr class="header">
				<th>&nbsp;</th>
				<th>Label</th>
				<th>House</th>
				<th>Year</th>
				<th>Month</th>
				<th>Temperature</th>
				<th>Daylight</th>
				<th>Energy Production</th>
			</tr>
			<tr class="<%= cycle('odd','even')%>">
				<th>&nbsp;</th>
				<td><%= @energy.label%></td>
				<td><%= @energy.house_id%></td>
				<td><%= @energy.year%></td>
				<td><%= @energy.month%></td>
				<td><%= @energy.temperature%></td>
				<td><%= @energy.daylight%></td>
				<td><%= @energy.energy_production%></td>
			</tr>
		</table>

		<div class="form-buttons">
			<%= form_tag(energy_path(@energy.id),:method=>"delete") do %>
  				<%= submit_tag('Delete Energy Record') %>
			<% end %>
		</div>
	<% end %>
	</fieldset>
</div>

app/views/energies/edit.html.erb
<% @page_title="Energy Edit"%>
<%= link_to("<< Back to Energy Record List",energies_path) %><br/>
<%= link_to("<< Back to House List",houses_path) %>

<div class="energies edit">
	<fieldset>
	<legend>Update Energy Record</legend>
	<%= form_for(:energy, :url=>{:action=>'update',:id=>@energy.id}) do |f|%>
		<%=render(:partial=>"form",:locals=>{:f=>f})%>
		<div>
			<%= form_tag(energy_path(@energy.id),:method=>"patch") do %>
				<%=submit_tag("Update Energy Record",:class=>"button")%>
			<% end %>
		</div>
	<% end%>
	</fieldset>
</div>

app/views/energies/index.html.erb
<% @page_title="Energies"%>
<div class="energies index">
	<h2>Energies</h2>

	<%= link_to("<< Back to House List",houses_path) %><br/>
	<%= link_to("AdminUser Page","/access/index") %><br/>
	<%= link_to("Add New Energy", new_energy_path)%>

	<div class="notice"><%= pluralize(@energies.size,'energy record')%> found</div>
	<table class="listing" summary="Energy list">
		<tr class="header">
			<th>&nbsp;</th>
			<th>Label</th>
			<th>House</th>
			<th>Year</th>
			<th>Month</th>
			<th>Temperature</th>
			<th>Daylight</th>
			<th>Energy Production</th>
			<th>Action</th>
		</tr>
		<% @energies.each do |energy| %>
		<tr>
			<td><%= energy.id%></td>
			<td><%= energy.label%></td>
			<td><%= energy.house_id%></td>
			<td><%= energy.year%></td>
			<td><%= energy.month%></td>
			<td><%= energy.temperature%></td>
			<td><%= energy.daylight%></td>
			<td><%= energy.energy_production%></td>
			<td class="actions">
				<%= link_to("Edit",edit_energy_path(energy.id),:class=>'action edit')%>
				<%= link_to("Delete",delete_energy_path(energy.id),:class=>'action delete')%>
			</td>
		</tr>
		<% end%>
	</table>
</div>

app/views/energies/new.html.erb
<%= link_to("<< Back to Energy Record List",energies_path) %><br />
<%= link_to("<< Back to House List",houses_path) %>

<div class="energies new">
	<fieldset>
	<legend>New Energy Record</legend>
	<%= form_for(:energy, :url=>{:action=>"create"}) do |f|%>
		<%=render(:partial=>"form",:locals=>{:f=>f})%>
		<div class="form-buttons">
			<%= form_tag(energies_path,:method=>"post") do %>
				<%=submit_tag("Create Energy Record")%>
			<% end %>
		</div>
	<% end%>
	</fieldset>
</div>

app/views/houses/_chart2.html.erb
<%= stylesheet_link_tag('chart2')%>

<div id="tooltip" class="hidden">
	<p><span id="Energy_Production">Default</span></p>
	<p><span id="Temperature">Default</span></p>
	<p><span id="Daylight">Default</span></p>
	<p><span id="Date">Default</span></p>
</div>
<%= javascript_tag do%> 
	//Width and height
	var w = 720;
	var h = 340;

	var padding=70;

	var x_offset=$("#chart2").offset().left;
	var y_offset=$("#chart2").offset().top;

	var data=$('.temp_information').data('temp');
	var dataset=[];
	var i=0;

	data.forEach(function(d) {
    	dataset[i]=d.energy_production;
    	i++;
  	});

  	var avg=mean(dataset);
  	var std_dev=std(dataset);
  	var high_threshold=avg+std_dev;
  	var low_threshold=avg-std_dev;

	var xScale = d3.scale.ordinal()
					.domain(d3.range(dataset.length))
					.rangeRoundBands([padding, w-padding], 0.05);
	var xScale2 = d3.scale.ordinal()
					.domain([data[0].date, data[data.length - 1].date])
					.rangeRoundBands([padding, w-padding], 0.05);

	var yScale = d3.scale.linear()
					.domain([0, d3.max(dataset)])
					.range([h-padding, 0]);
			
	//Create SVG element
	var svg2 = d3.select("#chart2")
				.append("svg")
				.attr("width", w)
				.attr("height", h);

	//Create bars
	svg2.selectAll("rect")
	   .data(dataset)
	   .enter()
	   .append("rect")
	   .attr("x", function(d, i) {
	   		return xScale(i);
	   })
	   .attr("y", function(d) {
	   		return yScale(d);
	   })
	   .attr("width", xScale.rangeBand())
	   .attr("height", function(d) {
	   		return h-yScale(d)-padding;
	   })
	   .attr("fill", function(d) {
			if (d>high_threshold) {
				return "red";
			}else{
				if (d<low_threshold){
				return "black";
				}else{
					return "teal";
				}	
			}
	   })
	   .attr("id","bar")
	   .on("mouseover", function(d,i) {

			//Get this bar's x/y values, then augment for the tooltip
			var xPosition = parseFloat(d3.select(this).attr("x")) + xScale.rangeBand() / 2 + x_offset;
			var yPosition = parseFloat(d3.select(this).attr("y")) / 2 + h / 2 + y_offset;

			//Update the tooltip position and value
			d3.select("#tooltip")
				.style("left", xPosition + "px")
				.style("top", yPosition + "px")						
				.select("#Energy_Production")
				.text("Energy Production: " + d);
			d3.select("#tooltip")
				.select("#Temperature")
				.text("Temperature: " + data[i].temperature);
			d3.select("#tooltip")
				.select("#Daylight")
				.text("Daylight: " + data[i].daylight);
			d3.select("#tooltip")
				.select("#Date")
				.text("Date: " + data[i].year+"-"+data[i].month);

			   
			//Show the tooltip
			d3.select("#tooltip").classed("hidden", false);

	   })
	   .on("mouseout", function() {
			   
			//Hide the tooltip
			d3.select("#tooltip").classed("hidden", true);
					
	   });
	bar_b=svg2.selectAll("rect");
	svg2.selectAll("rect")
		.on("click", function() {
	   		sortBars();
	    });

	//draw axes
	var xAxis = d3.svg.axis()
                  .scale(xScale2)
                  .tickFormat(d3.time.format("%Y-%m"))
                  .orient("bottom")



    var yAxis = d3.svg.axis()
                  .scale(yScale)
                  .orient("left")

    svg2.append("g")
    	.attr("class", "axis")
    	.attr("transform", "translate(0," + (h - padding) + ")")  
    	.call(xAxis);


    svg2.append("g")
    	.attr("class", "axis")
    	.attr("transform", "translate(" + padding + ",0)")
    	.call(yAxis)
    	.append("text")
      	.attr("transform", "rotate(-90)")
      	.attr("y", 6)
      	.attr("dy", ".3em")
      	.style("text-anchor", "end")
      	.text("Energy Production");



	//Define sort order flag
	var sortSwitch = false;
			
	//Define sort function
	var sortBars = function() {
		
		//Flip value of sortSwitch
	   	sortSwitch = !sortSwitch;
		bar_now=svg2.selectAll("rect");
		
		// sort or un-sort?
		if (sortSwitch){
			bar_now.sort(function(a, b) {
			   		return d3.ascending(a, b);
		   	})
		}else{
			bar_now=bar_b;
		}
		   
		bar_now.transition()
		   		.delay(function(d, i) {
			   		return i*50;
		   		})
		   		.duration(2000)
		   		.attr("x", function(d, i) {
		   			return xScale(i);
		   		});
	};			
			

	//Description
	svg2.append("text")
		.attr("x",w/2)
		.attr("y",h-38)
		.attr("font-size","16px")
		.attr("text-anchor","middle")
		.text("Bar Chart of Energy Productions");
	svg2.append("text")
		.attr("x",w/2)
		.attr("y",h-18)
		.attr("font-size","16px")
		.attr("text-anchor","middle")
		.text("(Click on any bar to sort/unsort; Hover on a bar for details)");
	svg2.append("text")
		.attr("x",w/2)
		.attr("y",h)
		.attr("font-size","13px")
		.attr("text-anchor","middle")
		.text("Red/Teal/Black: High/Medium/Low Production (thresholds:mean-std,mean+std)");

	//Mean calculation
	function mean(arr){
		var len=arr.length;
		var sum=0;
    	for(var i=0;i<len;i++){
    		sum=sum+parseFloat(arr[i]);
    	}
    	return sum/len;
	}

	//Variance calculation
	function variance(arr) {
    	var len=arr.length;
    	var sum=0;
    	for(var i=0;i<len;i++){
    		sum=sum+parseFloat(arr[i]);
    	}
    	var v=0;
    	if (len>1){
    		var mean=sum/len;
    		for(var i=0;i<len;i++){
    			v=v+(arr[i]-mean)*(arr[i]-mean);
    		}
    		return v/len;
    	}else{
    		return 0;
    	}
	}

	//Standard deviation
	function std(arr){
		return Math.sqrt(variance(arr));
	}

<% end %>	

app/views/houses/_form.html.erb
<%= error_messages_for(@house) %>

<table summary="House form fields">
	<tr>
		<th><%= f.label(:first_name,"First Name")%></th>
		<td><%= f.text_field(:first_name,:class=>"text")%></td>
	</tr>
	<tr>
		<th><%= f.label(:last_name,"Last name")%></th>
		<td><%= f.text_field(:last_name,:class=>"text")%></td>
	</tr>
	<tr>
		<th><%= f.label(:city)%></th>
		<td><%= f.text_field(:city,:class=>"text")%></td>
	</tr>
	<tr>
		<th><%= f.label(:num_of_people,"Number of People")%></th>
		<td><%= f.select(:num_of_people,1..20)%></td>
	</tr>
	<tr>
		<th><%= f.label(:has_child,"Has Child?")%></th>
		<td>
			<%= f.radio_button(:has_child,true)%> Yes
			<%= f.radio_button(:has_child,false)%> No
		</td>
	</tr>

</table>

app/views/houses/delete.html.erb
<% @page_title="House Delete"%>
<%= link_to("<< Back to House List",houses_path) %><br />
<%= link_to("<< Back to Energy Record List",energies_path) %>

<div class="houses delete">
	<fieldset>
	<legend>Update House</legend>

	<%= form_for(:house, :url=>{:action=>'destroy',:id=>@house.id}) do |f| %>

		<p><strong>Are you sure you want to delete this house?</strong></p>

		<table class="listing" summary="House list">
			<tr class="header">
				<th>&nbsp;</th>
				<th>First Name</th>
				<th>Last Name</th>
				<th>City</th>
				<th>Number of People</th>
				<th>Has Child?</th>
				<th>Number of Records</th>
			</tr>
			<tr class="<%= cycle('odd','even')%>">
				<th>&nbsp;</th>
				<td><%= @house.first_name%></td>
				<td><%= @house.last_name%></td>
				<td><%= @house.city%></td>
				<td><%= @house.num_of_people%></td>
				<td class="center"><%= @house.has_child ? 'Yes' : 'No' %></td>
				<td class="center"><%= @house.energies.size%></td>
			</tr>
		</table>

		<div>
			<%= form_tag(house_path(@house.id),:method=>'delete') do %>
  				<%= submit_tag('Delete House',:class=>"button") %>
			<% end %>
		</div>
	<% end %>
	</fieldset>
</div>

app/views/houses/edit.html.erb
<% @page_title="House Edit"%>
<%= link_to("<< Back to House List",houses_path) %><br />
<%= link_to("<< Back to Energy Record List",energies_path) %>

<div class="houses edit">
	<fieldset>
	<legend>Update House</legend>
	<%= form_for(:house, :url=>{:action=>'update',:id=>@house.id}) do |f|%>
		<%=render(:partial=>"form",:locals=>{:f=>f})%>
		<div>
			<%= form_tag(house_path(@house.id),:method=>'patch') do %>
  				<%=submit_tag("Update House",:class=>"button")%>
			<% end %>
		</div>
	<% end%>
	</fieldset>
</div>

app/views/houses/index.html.erb
<% @page_title="Houses"%>
<div class="houses index">
	<h2>Houses</h2>

	
	<%= link_to("<< Back to Energy Record List",energies_path) %><br />
	<%= link_to("AdminUser Page","/access/index") %><br/>
	<%= link_to("New House", new_house_path, :class=>'action_new')%>

	<div class="notice"><%= pluralize(@houses.size,'house')%> found</div>
	<table class="listing" summary="House list">
		<tr class="header">
			<th>&nbsp;</th>
			<th>First Name</th>
			<th>Last Name</th>
			<th>City</th>
			<th>Number of People</th>
			<th>Has Child?</th>
			<th>Number of Records</th>
			<th>Action</th>
		</tr>
		<% @houses.each do |house| %>
		<tr>
			<td><%= house.id%></td>
			<td><%= house.first_name%></td>
			<td><%= house.last_name%></td>
			<td><%= house.city%></td>
			<td><%= house.num_of_people%></td>
			<td class="center"><%= house.has_child ? 'Yes' : 'No' %></td>
			<td class="center"><%= house.energies.size%></td>
			<td class="actions">
				<%= link_to("Edit",edit_house_path(house.id))%>
				<%= link_to("Delete",delete_house_path(house.id))%>
				<%= link_to("Records",house_path(house.id))%>
			</td>
		</tr>
		<% end%>
	</table>
</div>

app/views/houses/new.html.erb
<% @page_title="New House"%>
<%= link_to("<< Back to House List",houses_path) %></br>
<%= link_to("<< Back to Energy Record List",energies_path) %>

<div class="houses new">
	<fieldset>
	<legend>Create House</legend>
	<%= form_for(:house, :url=>{:action=>'create'}) do |f|%>
		<%=render(:partial=>"form",:locals=>{:f=>f})%>
		<div class="form-buttons">
			<%= form_tag(houses_path,:method=>'post') do %>
  				<%=submit_tag("Create House")%>
			<% end %>
		</div>
	<% end%>
	</fieldset>
</div>

app/views/houses/show.html.erb
<% @page_title="Energy Records for One House"%>

<div id="links" class="span-24 border">
<%= link_to("<< Back to House List",houses_path) %><br/>
<%= link_to("<< Back to Energy Record List",energies_path) %><br/>
<%= link_to("AdminUser Page","/access/index") %><br/>
<%= link_to("Add New Energy", new_energy_path)%>
</div>

	<div id="house_info" class="span-6 border">
		<br/>
		<br/>
		<br/>
		<br/>
		<br/>
		<br/>
		<br/>
		<br/>
		<br/>
		<br/>
		<br/>
		<br/>
		<br/>
		<br/>
		<br/>
		<br/>
		<h3>House information</h3>
		<table summary="House information">
			<tr>
				<th>First Name</th>
				<td><%= @house.first_name %></td>
			</tr>
			<tr>
				<th>Last Name</th>
				<td><%= @house.last_name %></td>
			</tr>
			<tr>
				<th>City</th>
				<td><%= @house.city %></td>
			</tr>
			<tr>
				<th>Number of People</th>
				<td><%= @house.num_of_people %></td>
			</tr>
			<tr>
				<th>Has Child?</th>
				<td><%= @house.has_child ? 'Yes' : 'No' %></td>
			</tr>
		</table>
		<br/>
		<br/>
		<br/>
		<br/>
		<br/>
		<br/>
		<br/>
		<br/>
		<br/>
		<br/>
		<br/>
		<br/>
		<br/>
		<br/>
		<br/>
		<br/>
	</div>
	<div id="chart" class="span-18 last">
		<div id="chart1" class="span-18 last"></div>
		<div id="chart2" class="span-18 last"></div>	
	</div>
	<%= content_tag :div, class: "temp_information", data: {temp: @energies} do %>
	<% end %>	
	<%= render(:partial=>'chart1')%>
	<%= render(:partial=>'chart2')%>
	<div class="span-24">
	<h3>Energy Records</h3>
	<div class="notice"><%= pluralize(@energies.size,'energy record')%> found</div>
	<table class="listing" summary="Energy list">
		<tr class="header">
			<th>&nbsp;</th>
			<th>Label</th>
			<th>House</th>
			<th>Year</th>
			<th>Month</th>
			<th>Temperature</th>
			<th>Daylight</th>
			<th>Energy Production</th>
		</tr>
		<% @energies.each do |energy| %>
		<tr>
			<th>&nbsp;</th>
			<td><%= energy.label%></td>
			<td><%= energy.house_id%></td>
			<td><%= energy.year%></td>
			<td><%= energy.month%></td>
			<td><%= energy.temperature%></td>
			<td><%= energy.daylight%></td>
			<td><%= energy.energy_production%></td>
			<td class="actions">
				<%= link_to("Edit",edit_energy_path(energy.id),:class=>'action edit')%>
				<%= link_to("Delete",delete_energy_path(energy.id),:class=>'action delete')%>
			</td>
		</tr>
		<% end%>
	</table>
	</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EDSC 3 | <%= @page_title || "" %></title>
  <%= stylesheet_link_tag('screen',:media=>'screen, projection',:type=>'text/css')%>
  <%= stylesheet_link_tag('print',:media=>'print',:type=>'text/css')%>
  <!--[if lt IE 8]>
	<%= stylesheet_link_tag('ie',:media=>'screen, projection',:type=>'text/css')%>
  <![endif]-->

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="container">
	<div id="header"><h1>Energy Data Simulation Challenge 3</h1></div>
	<% if !flash[:notice].blank? %>
      <div class="success">
        <%= flash[:notice] %>
      </div>
  <% end %>
  <% if !flash[:error].blank? %>
  		<div class="error">
    		<%= flash[:error] %>
  		</div>
	<% end %>
	
	<%= yield %>

  <div id="footer">
    <p id="copyright">&copy;wangg</p>
  </div>
	
	</div>
  </body>

</html>